// Generated by https://quicktype.io

export interface Blog {
    _id:         string;
    category?:   Category;
    url:         string;
    title:       string;
    content:     string;
    slug?:       string;
    updatedAt?:  string;
    updated_by?: string;
}

export enum Category {
    Dashboard = "Dashboard",
    หน่วยงาน = "หน่วยงาน",
    อรรถประโยชน์อื่นๆ = "อรรถประโยชน์ อื่นๆ ",
    อรรถประโยชน์อื่นๆหน่วยงาน = "อรรถประโยชน์ อื่นๆ /หน่วยงาน",
    อรรถประโยชน์อื่นๆเกี่ยวกับพนักงาน = "อรรถประโยชน์ อื่นๆ /เกี่ยวกับพนักงาน",
    เกี่ยวกับพนักงานหน่วยงาน = "เกี่ยวกับพนักงาน/หน่วยงาน",
    เกี่ยวกับพนักงานอรรถประโยชน์อื่นๆ = "เกี่ยวกับพนักงาน/อรรถประโยชน์ อื่นๆ ",
    เว็บแอพระบบงาน = "เว็บ/แอพ ระบบงาน",
}
